name: Build APK
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
      - name: Build
        run: |
          cd zal_app
          flutter pub get
          flutter build apk --release --no-tree-shake-icons
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: zal-custom-apk
          path: zal_app/build/app/outputs/flutter-apk/app-release.apk
